version: 1.0.1

hote:           localhost
base:           framework
utilisateur:    root
mot_de_passe:   root

aNamespace:
    HTML: []
    data: 
      BaseAdminAction:   APP\Modules\Base\Controllers\BaseAdminAction
      Bdd:   APP\Modules\Base\Lib\Bdd